config/routes.rb
Petrefa::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :tarefas, only: [:create, :destroy]
  resources :pet, only: [:create, :destroy]
  root  'static_pages#home'
  match '/cadastro',  to: 'users#new',            via: 'get'
  match '/ajuda',    to: 'static_pages#help',    via: 'get'
  match '/desenvolvedores',   to: 'static_pages#about',   via: 'get'
  match '/login',  to: 'sessions#new',         via: 'get'
  match '/logout', to: 'sessions#destroy',     via: 'delete'

end

app/models/pet.rb
class Pet < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :nome, presence: true, length: { maximum: 15 }
end

app/models/tarefa.rb
class Tarefa < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order('created_at DESC') }
  validates :user_id, presence: true
  validates :descricao, presence: true, length: { maximum: 70 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :pet, dependent: :destroy
  has_many :tarefas, dependent: :destroy
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, length: { minimum: 6 }

  def feed
    Tarefa.where("user_id = ?", id)
  end

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :signed_in_user


  def create
    @pet = current_user.build_pet(pet_params)
    if @pet.save
      flash[:success] = "Seu pet está pronto!"
      redirect_to root_url
    else
      render 'static_pages/home'
    end
  end

  def destroy
  end

  private

    def pet_params
      params.require(:pet).permit(:nome)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or root_url
    else
      flash.now[:error] = 'Combinacao invalida de email e senha!'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @tarefa = current_user.tarefas.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
    @pet = current_user.build_pet if signed_in?
  end

  def about
  end
end

app/controllers/tarefas_controller.rb
class TarefasController < ApplicationController
  before_action :signed_in_user
  before_action :correct_user,   only: :destroy

  def create
    @tarefa = current_user.tarefas.build(tarefa_params)
    if @tarefa.save
      flash[:success] = "Tarefa criada!"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @tarefa.destroy
    redirect_to root_url
  end

  private

    def tarefa_params
      params.require(:tarefa).permit(:descricao, :prazo)
    end

    def correct_user
      @tarefa = current_user.tarefas.find_by(id: params[:id])
      redirect_to root_url if @tarefa.nil?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @tarefas = @user.tarefas.paginate(page: params[:page])
    #@pet = @user.pet
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Bem-vindo/a!"
      redirect_to(root_url)
    else
      render 'new'
    end
  end

  def new
    @user = User.new
  end

  def edit
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "Usuario deletado."
    redirect_to users_url
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Sucesso!"
      redirect_to(root_url)
    else
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    # Before filters

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "petRefa temporario"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to login_url, notice: "Por favor faça o login."
    end
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to "petRefa", root_path %>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Mobile",   '#' %></li>
      <li><%= link_to "Desenvolvedores", desenvolvedores_path %></li>
      <li><%= link_to "Ajuda", ajuda_path %></li>
      <li><a href="#">Rede Social</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to image_tag("logopequeno.png", alt: "LOGO PETREFA"), root_path, id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <% if signed_in? %>
              <% if current_user.admin? %>
              <li><%= link_to "Usuarios", users_path %></li>
              <% end %>
              <li><%= link_to "Ajustes",
                            edit_user_path(current_user) %></li>
              <li><%= link_to current_user.name, current_user %></li>
              <li><%= link_to "Logout", logout_path,
                                        method: "delete" %></li>
              <% else %>
              <li><%= link_to "Login", login_path %></li>
              <li><%= link_to "Cadastrar",    cadastro_path %></li>
              <% end %>
            </ul>
          </nav>
        </div>
      </div>
    </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
      <%= render 'layouts/header' %>
      <div class="container">
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
        <%= render 'layouts/footer' %>
        <%= debug(params) if Rails.env.development? %>
      </div>
  </body>
</html>

app/views/pets/_pet.html.erb
<%= image_tag("barracheia.gif") %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      O formulario contem <%= pluralize(object.errors.count, "erro") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="tarefas">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<% if current_user?(feed_item.user) %>
  <li id="<%= feed_item.id %>">
    <!-- <span class="categoria">
      <%= link_to feed_item.user.name, feed_item.user %>
    </span> -->
    <span class="descricao"><%= feed_item.descricao %></span>
    <span class="timestamp">
      Prazo: <%= feed_item.prazo %>.
    </span>
    <%= link_to "Feito!!", feed_item, method: :delete,
                                     data: { confirm: "Fez mesmo?" },
                                     title: feed_item.descricao %>
  </li>
<% end %>

app/views/shared/_pet_form.html.erb
<%= form_for(@pet) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :nome, placeholder: "Dê um nome para o seu petRefa." %>
  </div>
  <%= f.submit "Conhecer pet", class: "btn btn-small btn-default" %>
<% end %>

app/views/shared/_tarefa_form.html.erb
<%= form_for(@tarefa) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_field :descricao, placeholder: "O que devo fazer?" %>
  </div>
  <div class="input">
    <%= f.date_field :prazo %>
  </div>
  <%= f.submit "Criar Tarefa", class: "btn btn-small btn-default" %>
<% end %>

app/views/shared/_user_info.html.erb
<span>
  <%= pluralize(current_user.tarefas.count, "tarefa") %>
</span>

app/views/static_pages/about.html.erb
<% provide(:title, 'Desenvolvedores') %>
  <h1>Desenvolvedores</h1>
  <p>
    Pagina temporaria sobre desenvolvedores - petRefa.
  </p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Ajuda') %>
  <h1>Ajuda</h1>

app/views/static_pages/home.html.erb
<% if signed_in? %>
  <div id = "wrapper">
    <div id = "left">
      <div class="row">
        <aside class="span4">
          <section>
            <%= render 'shared/user_info' %>
          </section>
          <section>
            <%= render 'shared/tarefa_form' %>
          </section>
        </aside>
      </div>
      <div class="row">
        <aside class="span4">
            <h4>Tarefas</h4>
            <%= render 'shared/feed' %>
        </aside>
      </div>
    </div>
    <div id="pet">
      <%= render 'pets/pet' %>
    </div>
  </div>
<% else %>
  <div class="center hero-unit">
    <h1>petRefa</h1>
    <div class="row">
      <div class="span7 offset2">
        <%= form_for(:session, url: sessions_path) do |f| %>

          <%= f.label :email %>
          <%= f.text_field :email %>

          <%= f.label :password, "Senha" %>
          <%= f.password_field :password %>

          <%= f.submit "Login", class: "btn btn-small btn-default" %>
        <% end %>

        <p>Nao tem cadastro? <%= link_to "Crie uma conta!", cadastro_path %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/tarefas/_tarefa.html.erb
<li>
  <% if current_user?(tarefa.user) %>
    <span class="descricao"><%= tarefa.descricao %></span>

    <span class="timestamp">
      Prazo: <%= tarefa.prazo.strftime("%m/%d/%Y")  %>.
    </span>
    <%= link_to "Feito!", tarefa, method: :delete,
                                      data: { confirm: "Fez mesmo?" },
                                      title: tarefa.descricao %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Ajustes") %>
<h1>Ajustes</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name, "Nome" %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password, "Senha" %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmar Senha" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Salvar modificacoes", class: "btn btn-small btn-default" %>
    <% end %>

  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Todos os Usuarios') %>
<% if current_user.admin? %>
<h1>Todos os Usuarios</h1>

<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
      <% if !current_user?(user) %>
      | <%= link_to "deletar", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
      <% end %>
    </li>
  <% end %>
</ul>

<%= will_paginate %>
<% else %>
<h1>Você não tem permissão para ver esta página!</h1>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Cadastro') %>
<h1>Cadastro</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name, "Nome" %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password, "Senha" %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmar senha" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Criar conta!", class: "btn btn-small btn-default" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
    <aside class="span4">
      <% if @user.tarefas.any? %>
      <h3>Tarefas (<%= @user.tarefas.count %>)</h3>
      <ol class="tarefas">
        <%= render @tarefas %>
      </ol>
      <%= will_paginate @tarefas %>
      <% end %>
    </aside>
    <div id="pet">
        <h3><%= @user.pet.nil? ?  "Unicorniorefa" : @user.pet.nome %></h3>
        <%= render 'pets/pet' %>
    </div>
</div>